#pragma once

/* BEGIN_JUCE_MODULE_DECLARATION
    ID:                 jive_core
    vendor:             ImJimmi
    name:               JIVE Core
    license:            MIT
    dependencies:       juce_gui_basics
END_JUCE_MODULE_DECLARATION */

#define JIVE_CORE_H_INCLUDED

#include "algorithms/jive_Bezier.h"
#include "algorithms/jive_Find.h"
#include "algorithms/jive_Interpolate.h"
#include "algorithms/jive_TransferFunction.h"
#include "algorithms/jive_Visitor.h"
#include "compile-time-helpers/jive_JuceVersion.h"
#include "components/accessibility/jive_IgnoredComponent.h"
#include "components/canvases/jive_BackgroundCanvas.h"
#include "components/canvases/jive_Canvas.h"
#include "components/containers/jive_DocumentWindow.h"
#include "components/utilities/jive_HierarchyTraversal.h"
#include "components/widgets/jive_ImageComponent.h"
#include "components/widgets/jive_NormalisedProgressBar.h"
#include "components/widgets/jive_TextComponent.h"
#include "geometry/jive_BorderRadii.h"
#include "geometry/jive_BoxModel.h"
#include "geometry/jive_Length.h"
#include "geometry/jive_Orientation.h"
#include "graphics/jive_ComponentTypePredicates.h"
#include "graphics/jive_Fill.h"
#include "graphics/jive_FontUtilities.h"
#include "graphics/jive_Gradient.h"
#include "graphics/jive_LookAndFeel.h"
#include "graphics/jive_Styles.h"
#include "interface/jive_InteractionState.h"
#include "kinetics/jive_Easing.h"
#include "kinetics/jive_Transitions.h"
#include "logging/jive_ConsoleProgressBar.h"
#include "logging/jive_ScopeIndentedLogger.h"
#include "logging/jive_StringStreams.h"
#include "time/jive_TimeParser.h"
#include "time/jive_Timer.h"
#include "values/jive_Colours.h"
#include "values/jive_Event.h"
#include "values/jive_Object.h"
#include "values/jive_Property.h"
#include "values/jive_PropertyBehaviours.h"
#include "values/jive_ReferenceCountedValueTreeWrapper.h"
#include "values/jive_XmlParser.h"
#include "values/variant-converters/jive_AttributedStringVariantConverters.h"
#include "values/variant-converters/jive_FlexVariantConverters.h"
#include "values/variant-converters/jive_GridVariantConverters.h"
#include "values/variant-converters/jive_MiscVariantConverters.h"
#include "values/variant-converters/jive_VariantConvertion.h"
