include_guard()

option(JIVE_BUILD_BENCHMARKS "Build JIVE's benchmarks?" OFF)
option(JIVE_BUILD_DEMO_RUNNER "Build JIVE's demo runner?" OFF)
option(JIVE_BUILD_EXAMPLES "Build JIVE's examples?" OFF)
option(JIVE_BUILD_TEST_RUNNER "Build JIVE's test runner?" OFF)
option(JIVE_ENABLE_COVERAGE "Generate coverage reports when running tests?" OFF)
option(JIVE_ENABLE_MELATONIN_INSPECTOR "Add the component inspector to the demos and examples?" OFF)
option(JIVE_ENABLE_PLUGINVAL "Add pluginval tests for the demo plugins?" OFF)
option(JIVE_ENABLE_PROJUCER_PROJECTS "Add Projucer targets?" OFF)
option(JIVE_ENABLE_SANITISERS "Enable ASan, LSan, UBSan?" OFF)
