name: Demo Runner

on:
    pull_request:
        branches: [main]

jobs:
    build:
        strategy:
            matrix:
                runner: [macos-latest, windows-latest]
                include:
                    - generator: Xcode
                      runner: macos-latest
                      name: macOS
                    - generator: Visual Studio 17
                      runner: windows-latest
                      name: Windows

        name: Build Demo ${{matrix.name}}
        runs-on: ${{matrix.runner}}
        defaults:
            run:
                shell: bash
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: "recursive"

            - name: CMake Configure
              run: cmake -Bbuild -G "${{matrix.generator}}" -DJIVE_BUILD_DEMO_RUNNER=ON

            - name: CMake Build
              run: cmake --build build --config Release
