name: Test Runner

on:
    pull_request:
        branches: [main]

env:
    BUILD_TYPE: Debug

defaults:
    run:
        shell: bash

jobs:
    test-windows:
        name: Test Windows
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: "recursive"

            - name: Configure CMake
              run: cmake -Bbuild -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DJIVE_BUILD_TEST_RUNNER=ON

            - name: Build
              run: cmake --build build --config ${{env.BUILD_TYPE}}

            - name: Test
              run: cd build && ctest -j14 -C Debug -T test --output-on-failure --extra-verbose

    test-macos:
        name: Test macOS
        runs-on: macos-latest

        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: "recursive"

            - name: Configure CMake
              run: cmake -Bbuild -GXcode -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DJIVE_BUILD_TEST_RUNNER=ON -DJIVE_ENABLE_COVERAGE=ON -DJIVE_ENABLE_SANITISERS=ON

            - name: Build
              run: cmake --build build --config ${{env.BUILD_TYPE}}

            - name: Test
              run: cd build && ctest -j14 -C Debug -T test --output-on-failure

    verify-formatting:
        name: Verify Formatting
        runs-on: macos-latest

        steps:
            - uses: actions/checkout@v4

            - name: Install clang-format
              run: brew install clang-format

            - name: Verify formatting
              run: python3 .github/scripts/verify_formatting.py
